"""
This type stub file was generated by pyright.
"""

"""Provides the code to load PRAW's configuration file ``praw.ini``."""
class _NotSet:
    def __bool__(self) -> bool:
        ...
    
    __nonzero__ = ...
    def __str__(self) -> str:
        ...
    


class Config:
    """A class containing the configuration for a Reddit site."""
    CONFIG = ...
    CONFIG_NOT_SET = ...
    LOCK = ...
    INTERPOLATION_LEVEL = ...
    @property
    def short_url(self) -> str:
        """Return the short url.

        :raises: :class:`.ClientException` if it is not set.

        """
        ...
    
    def __init__(self, site_name: str, config_interpolation: str | None = ..., **settings: str) -> None:
        """Initialize a :class:`.Config` instance."""
        ...
    


