"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Any

import praw

"""Provide the PRAWBase superclass."""
if TYPE_CHECKING:
    ...
class PRAWBase:
    """Superclass for all models in PRAW."""
    @classmethod
    def parse(cls, data: dict[str, Any], reddit: praw.Reddit) -> Any:
        """Return an instance of ``cls`` from ``data``.

        :param data: The structured data.
        :param reddit: An instance of :class:`.Reddit`.

        """
        ...
    
    def __init__(self, reddit: praw.Reddit, _data: dict[str, Any] | None) -> None:
        """Initialize a :class:`.PRAWBase` instance.

        :param reddit: An instance of :class:`.Reddit`.

        """
        ...
    


