"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

import praw.models

from .base import PRAWBase

"""Provide the ModAction class."""
if TYPE_CHECKING:
    ...
class ModAction(PRAWBase):
    """Represent a moderator action."""
    @property
    def mod(self) -> praw.models.Redditor:
        """Return the :class:`.Redditor` who the action was issued by."""
        ...
    
    @mod.setter
    def mod(self, value: str | praw.models.Redditor): # -> None:
        ...
    


