"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Iterator

import praw.models

from ...base import PRAWBase

"""Provide the SubmissionListingMixin class."""
if TYPE_CHECKING:
    ...
class SubmissionListingMixin(PRAWBase):
    """Adds additional methods pertaining to :class:`.Submission` instances."""
    def duplicates(self, **generator_kwargs: str | int | dict[str, str]) -> Iterator[praw.models.Submission]:
        """Return a :class:`.ListingGenerator` for the submission's duplicates.

        Additional keyword arguments are passed in the initialization of
        :class:`.ListingGenerator`.

        Example usage:

        .. code-block:: python

            submission = reddit.submission("5or86n")

            for duplicate in submission.duplicates():
                # process each duplicate
                ...

        .. seealso::

            :meth:`.upvote`

        """
        ...
    


