"""
This type stub file was generated by pyright.
"""

from ..util import _deprecate_args

"""Provide classes related to inline media."""
class InlineMedia:
    """Provides a way to embed media in self posts."""
    TYPE = ...
    def __eq__(self, other: InlineMedia) -> bool:
        """Return whether the other instance equals the current."""
        ...
    
    @_deprecate_args("path", "caption")
    def __init__(self, *, caption: str = ..., path: str) -> None:
        """Initialize an :class:`.InlineMedia` instance.

        :param caption: An optional caption to add to the image (default: ``None``).
        :param path: The path to a media file.

        """
        ...
    
    def __repr__(self) -> str:
        """Return an object initialization representation of the instance."""
        ...
    
    def __str__(self) -> str:
        """Return a string representation of the media in Markdown format."""
        ...
    


class InlineGif(InlineMedia):
    """Class to provide a gif to embed in text."""
    TYPE = ...


class InlineImage(InlineMedia):
    """Class to provide am image to embed in text."""
    TYPE = ...


class InlineVideo(InlineMedia):
    """Class to provide a video to embed in text."""
    TYPE = ...


