"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Any

import praw.models

from ...util import _deprecate_args
from ..base import PRAWBase

"""Provide the MoreComments class."""
if TYPE_CHECKING:
    ...
class MoreComments(PRAWBase):
    """A class indicating there are more comments."""
    def __eq__(self, other: str | MoreComments) -> bool:
        """Return ``True`` if these :class:`.MoreComments` instances are the same."""
        ...
    
    def __init__(self, reddit: praw.Reddit, _data: dict[str, Any]) -> None:
        """Initialize a :class:`.MoreComments` instance."""
        ...
    
    def __lt__(self, other: MoreComments) -> bool:
        """Provide a sort order on the :class:`.MoreComments` object."""
        ...
    
    def __repr__(self) -> str:
        """Return an object initialization representation of the instance."""
        ...
    
    @_deprecate_args("update")
    def comments(self, *, update: bool = ...) -> list[praw.models.Comment]:
        """Fetch and return the comments for a single :class:`.MoreComments` object."""
        ...
    


