"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Contains functions dealing with snake case conversions."""
_re_camel_to_snake = ...
def camel_to_snake(name: str) -> str:
    """Convert ``name`` from camelCase to snake_case."""
    ...

def snake_case_keys(dictionary: dict[str, Any]) -> dict[str, Any]:
    """Return a new dictionary with keys converted to snake_case.

    :param dictionary: The dict to be corrected.

    """
    ...

