"""
This type stub file was generated by pyright.
"""

from .base import BaseList

"""Provide the DraftList class."""
class DraftList(BaseList):
    """A list of :class:`.Draft` objects. Works just like a regular list."""
    CHILD_ATTRIBUTE = ...


