"""
This type stub file was generated by pyright.
"""

from .base import BaseList

"""Provide the ModeratedList class."""
class ModeratedList(BaseList):
    """A list of moderated :class:`.Subreddit` objects. Works just like a regular list."""
    CHILD_ATTRIBUTE = ...


