"""
This type stub file was generated by pyright.
"""

from .base import BaseList

"""Provide the RedditorList class."""
class RedditorList(BaseList):
    """A list of :class:`.Redditor` objects. Works just like a regular list."""
    CHILD_ATTRIBUTE = ...


