"""
This type stub file was generated by pyright.
"""

from .base import BaseList

"""Provide the TrophyList class."""
class TrophyList(BaseList):
    """A list of :class:`.Trophy` objects. Works just like a regular list.

    This class is solely used to parse responses from Reddit, so end users should not
    use this class directly.

    """
    CHILD_ATTRIBUTE = ...


