"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

import praw

from .mixins import BaseListingMixin, RisingListingMixin

"""Provide the DomainListing class."""
if TYPE_CHECKING:
    ...
class DomainListing(BaseListingMixin, RisingListingMixin):
    """Provide a set of functions to interact with domain listings."""
    def __init__(self, reddit: praw.Reddit, domain: str) -> None:
        """Initialize a :class:`.DomainListing` instance.

        :param reddit: An instance of :class:`.Reddit`.
        :param domain: The domain for which to obtain listings.

        """
        ...
    


